### PR TITLE
Fix VID Validation

### LINKED ISSUE #116: Fix VID Validation
Currently, VID validation is broken due to apparent Wasm I/O limits. Now that we use Aztec's SRS, which is ~200MB, the JIT validator seems to balk. 

There is a potentially simple fix. If we pre-truncate the SRS by lowering the degree variable of the Aztec SRS [generation function ](https://github.com/EspressoSystems/nitro-espresso-integration/blob/ef03d22875b5e4c9c6c23b04675bd550e5ab6f5a/arbitrator/espresso-crypto-helper/src/lib.rs#L220), we can lower the size of the SRS while remaining consistent with the SRS that HotShot uses, which should be trimmed anyway.

### PR DESCRIPTION
**Pull request by nomaxg**
Closes #116 

### This PR:
Fixes VID validation by moving ark-srs to dev-dependencies, which enabled some downstream ark parallelism that WASM does not like. 

### How to test this PR:

go test -timeout 30s -run ^TestEspressoJitMachine$ github.com/offchainlabs/nitro/system_tests -v

### CODE REVIEW

File: cmd/replay/main.go [hunk 1]
```diff
@@ -308,7 +308,7 @@ func main() {
 			}
 			// TODO https://github.com/EspressoSystems/nitro-espresso-integration/issues/116
 			// Uncomment when validation is fixed
```
Comment (ImJeremyHe) [inline cmd/replay/main.go:310]: Remove these?

**Review by ImJeremyHe — APPROVED** [review]

**Comment by ImJeremyHe** [comment]
I think CI is broken now. If the switch test and e2e test can pass locally, it is okay to merge this PR.
